### ISSUE TITLE
[PSyIR] FortranReader.psyir_from_file() get NoMatchError error

### ISSUE THREAD

**Issue by svalat** [stfc/PSyclone#2009]
Hi,
I'm trying to play with PSyIR on Croco code and get an issue while parsing fortran with the master branch of PSyIR.

The same case is working well in PSyClone commit 3bb8ced29.

Calling directly fparser of psyclone on the fortran file also work fine even with master.

```
Traceback (most recent call last):
  File "/home/svalat/Projects/croco_test/venv/lib/python3.10/site-packages/fparser/two/Fortran2003.py", line 237, in __new__
    return Base.__new__(cls, string)
  File "/home/svalat/Projects/croco_test/venv/lib/python3.10/site-packages/fparser/two/utils.py", line 428, in __new__
    raise NoMatchError(errmsg)
fparser.two.utils.NoMatchError: at line 5
>>>     &                                        , node,  nnodes


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svalat/Projects/croco_test/CONFIGS/BASIN_DSL_TEST/compile_src/./reproduce.py", line 6, in <module>
    psyir_tree = reader.psyir_from_file("lib/insert_node.f_pass1")
  File "/home/svalat/Projects/croco_test/venv/lib/python3.10/site-packages/psyclone/psyir/frontend/fortran.py", line 197, in psyir_from_file
    return self.psyir_from_source(source.read())
  File "/home/svalat/Projects/croco_test/venv/lib/python3.10/site-packages/psyclone/psyir/frontend/fortran.py", line 77, in psyir_from_source
    parse_tree = self._parser(string_reader)
  File "/home/svalat/Projects/croco_test/venv/lib/python3.10/site-packages/fparser/two/Fortran2003.py", line 241, in __new__
    raise FortranSyntaxError(string, "")
fparser.two.utils.FortranSyntaxError: at line 5
>>>     &                                        , node,  nnodes
```
I can reproduce with the given fortran code.
The issue looks related the the &.... line which is fixed if we moved up `node` & `nnodes` in a single line.

```fortran
      subroutine insert_node (name, lstr, node, nnodes, ierr)
      integer*4 lstr, ierr, i,j,k, lsffx, digits, power, ndots, idot(3)
     &                                        , node,  nnodes
      end
```
Reproduced by doing:

```python
#!/usr/bin/env python3

from psyclone.psyir.frontend.fortran import FortranReader

reader = FortranReader()
psyir_tree = reader.psyir_from_file("lib/insert_node.f_pass1")
```
Not sure if I need to report to you or fparser ?

Thanks in advance.

**Comment by arporter** [comment]
subroutine insert_node (name, lstr, node, nnodes, ierr)
      integer*4 lstr, ierr, i,j,k, lsffx, digits, power, ndots, idot(3)
     &                                        , node,  nnodes
      end

Is that really the code that you've got as that's not valid Fortran - it needs a `&` at the end of the line being continued - i.e. after `idot(3)`?

**Comment by arporter** [comment]
Oh, unless CROCO uses fixed-format Fortran??

**Comment by svalat** [comment]
yes I think it is fixed format.

**Comment by arporter** [comment]
Ah, that's it. The Fortran frontend (silently) defaults to specifying free-format code. That is a bit of an oversight on our part that we'll have to fix. (For now you could edit L76 of psyclone/psyir/frontend/fortran.py and change the arguments to the `FortranFormat` constructor to be `False, False`.)

**Comment by svalat** [comment]
I confirm this was the issue. We have both fixed form and free form in CROCO. I made a patch adding a parameter to your functions. If you want I can make a PR (if you didn't yet made one).

Two ways : 
  - either adding a free_form optional option to `psyir_from_file` and `psyir_from_source`, 
  - or add a parameter into the class itself ?

**Comment by arporter** [comment]
Closing as #2014 was merged.
