### ISSUE TITLE
doctest issue(s) - e.g. LFRicTypes created before config is loaded

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2088]
While trying to set up some new doctests, I had problems with ``make doctest`` in the developer guide now and again failing. Root cause seems to be the order in which doctest is running, which seems to be pseudo-random. If ``psyir.rst`` is processed first, we get the exception that LFRicType is used before a config is loaded:
```
$ make doctest
sphinx-build -b doctest -d _build/doctrees   . _build/doctest
Running Sphinx v6.1.3
loading pickled environment... checking bibtex cache... up to date
done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [doctest]: targets for 16 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] psy_data                                                                                                                                               
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/joerg/work/psyclone/doc/developer_guide/developers_gocean1p0_stencils.rst: WARNING: document isn't included in any toctree
done
running tests...

Document: psyir
---------------
**********************************************************************
File "../../src/psyclone/domain/lfric/lfric_types.py", line ?, in default
Failed example:
    num_dofs_class = LFRicTypes("NumberOfUniqueDofsDataSymbol")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[1]>", line 1, in <module>
        num_dofs_class = LFRicTypes("NumberOfUniqueDofsDataSymbol")
      File "/home/joerg/work/psyclone/src/psyclone/domain/lfric/lfric_types.py", line 95, in __new__
        LFRicTypes.init()
      File "/home/joerg/work/psyclone/src/psyclone/domain/lfric/lfric_types.py", line 122, in init
        LFRicTypes._create_precision_from_const_module()
      File "/home/joerg/work/psyclone/src/psyclone/domain/lfric/lfric_types.py", line 146, in _create_precision_from_const_module
        lfric_const = LFRicConstants()
      File "/home/joerg/work/psyclone/src/psyclone/domain/lfric/lfric_constants.py", line 65, in __init__
        raise InternalError("LFRicConstants is being created before the "
    psyclone.errors.InternalError: PSyclone internal error: LFRicConstants is being created before the config file is loaded

```
I tried to fix this by loading the config object in testsetup:
```
+.. testsetup::
+
+    from psyclone.configuration import Config
+    Config.get().api = "nemo"
+
+
```
But that does not seem to fix the problem. I actually have the feeling that the testsetup is just not executed (based on my test). 

In order to remove the random order, I tried to use `python -m doctest ./psyir.rst` , but this call certainly ignored testsetup. I tried this by adding syntactically incorrect code to the testsetup, and it did not trigger any errors :(

Even my newly added ..testcode:: does not seem to be actually tested (again, adding incorrect syntax did not trigger a message, nor did the #tests increase), only if I used `>>>` at the beginning did it work (and similarly, I assume the tests that do work are from python dochtests imported that use `>>>`.

I am pretty certain that this wasn't the case in the past - could someone verify if the testcode is actually executed (e.g. dependency.rst, again, add some incorrect python code which should then trigger a failure)? 

It is possible that I have something missing (I recently upgraded my ubuntu release and did notice a few modules missing), but I do not get any message or so :(

**Comment by arporter** [comment]
I've just tried with master and `make doctest` in the developer guide works for me (I tried repeatedly). I then tried `python -m doctest ./psyir.rst` and that failed.

**Comment by hiker** [comment]
Seems to be related to my sphinx version: 6.1.3 has the problem, going back to 5.3.0 fixed the issue.

I leave this (now renamed) issue open till we can figure out what we need to do to support sphinx 6

**Comment by sergisiso** [comment]
`make doctest` has many broken tests, I started fixing them.

Note that `pytest -n 16 --doctest-modules src/psyclone/` tests the snippets coming from code docstring and produces much better error messages (with actual line number that you can follow), while the sphinx falieues are often hard to understand.

I will add both the the CI

**Comment by sergisiso** [comment]
Another problem is that doctests have paths hardcoded, but this is problematic because their location is not consistent:
- for pytest the root is the repo root
- for sphinx the root is the doc directory
- for testing after being distributed in pip or spack fortran file are moved to the share directory

The correct way to address files seems to be with `importlib.resources`
