### ISSUE TITLE
SymPy - array access with and without index in one expression

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2122]
The following two expressions causes an exception:
```
 sym_maths.equal(psyir_of("A"), psyir_of("A(i)"))
 sym_maths.equal(psyir_of("A(i)"), psyir_of("A"))
```
trigger two problems:
1. TypeError: 'Symbol' object is not callable (for the first example)
2. TypeError: unsupported operand type(s) for -: 'a' and 'UndefinedFunction'

Caused by inconsistencies in using 'a' as scalar or as a sympy function. @rupertford indicated that enforcing a symbol to be a sympy function if there is at least one array access helps.

**Comment by hiker** [comment]
While sympy supports matrixes (and a vector is a 1d matrix), it does not support using symbols as indices E.g.:
```
>>> f = sp.Matrix([[x, x, y]])    #x, y all sympy symbols
>>> sp.solvers.solveset(f[0]-f[2], x)
{y}
>>> i=sp.Symbol("i")
>>> sp.solvers.solveset(f[0]-f[i], x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joerg/.local/lib/python3.10/site-packages/sympy/matrices/repmatrix.py", line 233, in __getitem__
    return _getitem_RepMatrix(self, key)
  File "/home/joerg/.local/lib/python3.10/site-packages/sympy/matrices/repmatrix.py", line 750, in _getitem_RepMatrix
    values = [rep.getitem(*divmod(index_(key), cols))]
TypeError: 'Symbol' object cannot be interpreted as an integer
```

So, changing the current implementation (which represents arrays as functions) to using vectors does not work, since in general we will have symbols as indices :(

Not sure how to fix this, short of detecting if we have inconsistent usage patterns (`a` and `a(i)`), and then return that the results are not equal - tough

**Comment by rupertford** [comment]
`sym_maths.equal` is being used when we translate an `invoke` in the algorithm layer into a call to the generated psy-layer. Specifically it is used to avoid duplicate arguments when there are multiple kernels within an invoke. For example:

```
call invoke(kern1(a,b), kern2(b,c))
```
becomes
```
call invoke_0(a,b,c)
```
Previously we used a simple text comparison but then something like `a(i+1)` and `a(1+i)` would be considered to be different so I thought it nicer/better to use `sym_math.equal`.

At the moment arguments to kernels within an invoke are limited to literals, arrays and indexed arrays. In the future we might relax this and allow more general expressions.

**Comment by rupertford** [comment]
Could we replace non-indexed arrays with indexed arrays using a custom index?

**Comment by hiker** [comment]
@rupertford just to clarify: if you have (say) `a(i)` and `a(i+1)` as arguments, I assume you would supply them both? Or would you just supply `a`, and then the indices?

And same question if you have `a` and `a(i)` - I assume you provide both arguments then?

Yes, maybe defining a dummy (otherwise unknown) symbol would work, but it could also result in giving spurious results back from sympy - eg. `sympy.solve(a(i)-a(j))` returns `[{i: j}]`.

I also noticed that there is a 'is_same_array` method in `array_mixin`, which seems to do pretty much what you want - and it appears (I didn't check in great detail) to support comparison of an array with a normal Reference. The only missing bit would be to use sympy when comparing the indices, e.g.:
```
        # Examine the indices, ignoring any on the innermost accesses (hence
        # the slice to `depth` rather than `depth + 1` below).
        for idx1, idx2 in zip(self_indices[:depth], node_indices[:depth]):
            if idx1 != idx2:
                return False
        return True
```
The comparison `idx1 != idx2` should be using sympy. And I don't understand why it is not comparing the last index, so maybe it is a very special function?

What about using `__eq__`? From what I can see, it is only implemented for Reference. My suggestion at this stage would be to implement this for `array_mixin` (very similar to the `is_same_array` function), if we agree that `a` and `a(i)` is not the same.

**Comment by rupertford** [comment]
Yes, we can get away with limiting it to references in my case. If replacing `b` with `b(X)` is a general solution then would it not make more sense to do that?

**Comment by hiker** [comment]
I am actually considering fixing array ranges as well (#1655 and #1537, seems to be duplicates) - if I start modifying the expressions to include a new variable, I might as well do the rest and get it all fixed.

Hence, if it's only reference, I could handle this as special case in sympy for now, and this work around would be removed in #1537/1655. Sorry for the delays with this, I've spent quite a bit of time looking into sympy again.

**Comment by hiker** [comment]
@rupertford Just FYI, I am fixing this as part of #1537 - just adding proper support for array expressions (which includes just using an array without any indices). This is all working nice so far (as long as I can query the symbol table to reliably identify arrays of course), as long as no user defined types are used (they work for reasoning about, but you can't `expand` and use the sympy expression to rewrite Fortran code). I might have an idea to support this as well.

**Comment by arporter** [comment]
I think this one can be closed now @hiker?
