### ISSUE TITLE
PSyclone fails to handle some Functions with return type kind definitions

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2194]
Another Socrates related error - this time it seems to be a PSyclone error.

The file in question has this declaration (which I believe to be the cause, but may be incorrect:
```
REAL(RealK) FUNCTION rayleigh_scatter(...)

  USE realtype_rd, ONLY: RealK
```

Running PSyclone on this file causes this crash:
```
(LFRIC_env) [achalk@glados bin]$ psyclone -I /home/achalk/socrates_2304/bin/ -api nemo rayleigh_scatter.f90
Error, unexpected exception, please report to the authors:
Traceback (most recent call last):
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/symbols/symbol_table.py", line 847, in lookup
    symbol = self.get_symbols(scope_limit)[self._normalize(name)]
KeyError: 'realk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 649, in _kind_find_or_create
    kind_symbol = symbol_table.lookup(lower_name)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/symbols/symbol_table.py", line 873, in lookup
    from err
KeyError: "Could not find 'realk' in the Symbol Table."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/generator.py", line 510, in main
    kern_naming=args.kernel_renaming)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/generator.py", line 269, in generate
    .create(invoke_info)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyGen.py", line 228, in create
    return PSyClass(invoke_info)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/nemo.py", line 131, in __init__
    psyir = processor.generate_psyir(ast)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 1155, in generate_psyir
    self.process_nodes(node, [parse_tree])
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 2535, in process_nodes
    psy_child = self._create_child(child, parent)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 2598, in _create_child
    return handler(child, parent)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 4605, in _program_handler
    self.process_nodes(file_container, node.children)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 2535, in process_nodes
    psy_child = self._create_child(child, parent)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 2598, in _create_child
    return handler(child, parent)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 4411, in _subroutine_handler
    base_type, _ = self._process_type_spec(parent, child)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 1700, in _process_type_spec
    precision = self._process_precision(type_spec, parent)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 2518, in _process_precision
    return _kind_find_or_create(str(kind_names[0]), symbol_table)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 693, in _kind_find_or_create
    visibility=symbol_table.default_visibility)
  File "/home/achalk/LFRIC/PSyclone/src/psyclone/psyir/frontend/fparser2.py", line 346, in _find_or_create_imported_symbol
    raise SymbolError(f"No Symbol found for name '{name}'.")
psyclone.psyir.symbols.symbol.SymbolError: PSyclone SymbolTable error: No Symbol found for name 'realk'.
```

I think what is happening is that the process_precision call for the return type of the function does not consider looking for the kind argument in the functions own symbol table. Instead it only searches the node's parents - this is probably a special case for `Function`s, so we could handle this differently if we have a Node that is a Routine where `return_symbol is not None`

The recursion is handled anyway (so if the USE was at a module level we'd still find it correctly I think), so that may be the only fix required.

**Comment by LonelyCat124** [comment]
Potential fix:
`psyir/frontend/fparser2.py` line 4410
change:
`                    base_type, _ = self._process_type_spec(parent, child)`
to
`                    base_type, _ = self._process_type_spec(routine, child)`
