### ISSUE TITLE
dev-doctest failing after upgrade of Sphinx

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2288]
The GHA doctest check has recently started failing. I was able to reproduce this locally after I upgraded my version of Sphinx:

    File "interface_example.py", line ?, in default
    Failed example:
      alg, psy = generate(SOURCE_FILE, api=API)
    Exception raised:
      Traceback (most recent call last):
      File "/home/kbc59144/.pyenv/versions/3.10.7/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[2]>", line 1, in <module>
        alg, psy = generate(SOURCE_FILE, api=API)
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/generator.py", line 381, in generate
        invoke_trans.apply(
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py", line 210, in apply
        arguments = self.get_arguments(node, options=options)
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/domain/gocean/transformations/gocean_alg_invoke_2_psy_call_trans.py", line 74, in get_arguments
        self._add_arg(arg, arguments)
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py", line 130, in _add_arg
        if sym_maths.equal(arg, existing_arg):
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/core/symbolic_maths.py", line 102, in equal
        diff = SymbolicMaths._subtract(exp1, exp2)
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/core/symbolic_maths.py", line 191, in _subtract
        sympy_expressions = SymPyWriter(exp1, exp2)
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/psyir/backend/sympy_writer.py", line 168, in __new__
        return writer(expressions)
      File "/home/kbc59144/Projects/PSyclone/src/psyclone/psyir/backend/sympy_writer.py", line 388, in __call__
        result.append(parse_expr(expr, self.type_map))
      File "/home/kbc59144/.pyenv/versions/3.10.7/envs/psyclone310/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py", line 1049, in parse_expr
        exec('from sympy import *', global_dict)
      File "<string>", line 1, in <module>
    AttributeError: module 'sympy' has no attribute 'external'

Does that ring any bells @hiker?

**Comment by arporter** [comment]
Assigning @hiker as he's our Sympy expert :-) Not necessarily expecting you to fix it though Joerg!

**Comment by arporter** [comment]
Weirdly, I've just upgraded to `sphinxcontrib-devhelp-1.0.5` (from 1.0.2) and the error goes away. Maybe it's not our problem?

**Comment by arporter** [comment]
I've just checked `setup.py` and the RTD yaml and we don't pin versions of these packages anywhere (AFAICS).

**Comment by hiker** [comment]
Some of the failures seems to be correct, e.g.:
```
     >>> ast, invokeInfo = parse(FILENAME, api=API)
     >>> psy = PSyFactory(API, distributed_memory=False).create(invoke_info)
```
My feeling ... these lines were not executed before, but now are??

**Comment by hiker** [comment]
I seem to be able to reproduce the issue if I do a `make clean` before the `make doctest`. Not that it helps much with finding the root of the problem :P

**Comment by arporter** [comment]
Oh yes, doing a `make clean` breaks it for me too. I suggest we do a `make html` first with a comment to say why.
